# -*- coding: utf-8 -*-
"""Zero-shot route recomputation (the Section 3.4 control; added at submission time).

Background: the source-calibrated control of Table 5 evaluates coverage with the test residuals of
the fine-tuned (deployed) model. To test whether the naive choice of drawing q_src and the evaluated
residuals from different models affects the conclusion, this recomputation instead uses zero-shot
(un-fine-tuned) test residuals: calibration quantile and prediction function both come from the source model, with only the evaluation data in the target domain (same split, seed and standardization protocol).

Data source: results_cx2/conformal/t4zs_<model>_s<seed>.json
        (generated by code/conformal/t4_conformal_local.py --zs-only, 20 configurations)

Recomputed and asserted (as reported in Section 3.4):
  * the 20 runs (2 target domains x 2 backbones x 5 seeds) cover 0.0000-0.0240, all below nominal 0.90
    (control: the fine-tuned scope gives 0.000-0.252)
  * zero-shot test-residual medians are about 21-46x q_src (the residual-scale mismatch is the direct quantity behind the coverage collapse)
Run: python code/checks/zeroshot_route.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RES = ROOT / "results_cx2" / "conformal"
ROWS, BAD = [], []


def check(label, expect, got, tol):
    ok = abs(got - expect) <= tol
    ROWS.append((label, expect, got, ok))
    if not ok:
        BAD.append(label)


covs, ratios = [], []
for model in ("tcn", "lstm"):
    for seed in (42, 43, 44, 45, 46):
        d = json.load(open(RES / f"t4zs_{model}_s{seed}.json", encoding="utf-8"))
        for dom in ("CALCE", "NASA"):
            t = d["targets"][dom]
            zs = t["zero_shot"]
            # independent recomputation: weight per-cell (window count x coverage) into the total coverage and compare with the stored value
            cells = t["per_cell"]
            n_tot = sum(c["n_windows"] for c in cells.values())
            cov_rec = sum(c["n_windows"] * c["cov_src_zeroshot"] for c in cells.values()) / n_tot
            check(f"{model}/s{seed}/{dom} PICP recomputation matches", zs["PICP_src_zeroshot"], cov_rec, 1e-9)
            covs.append(zs["PICP_src_zeroshot"])
            ratios.append(zs["med_abs_r"] / d["q_src"])

check("minimum coverage over 20 runs", 0.0000, min(covs), 5e-4)
check("maximum coverage over 20 runs", 0.0240, max(covs), 5e-4)
check("all 20 runs below nominal 0.90", 1, 1 if all(v < 0.90 for v in covs) else 0, 0)
check("median residual / q_src lower bound", 21.3, min(ratios), 0.2)
check("median residual / q_src upper bound", 46.2, max(ratios), 0.2)

w1 = max(len(r[0]) for r in ROWS)
for label, expect, got, ok in ROWS:
    print("%-*s  %-14.4f %-14.4f %s" % (w1, label, expect, got, "match" if ok else "MISMATCH <--"))
print("-" * 72)
if BAD:
    print("%d items do not match:" % len(BAD), BAD)
    raise SystemExit(1)
print("All %d reported numbers match the manuscript." % len(ROWS))
